error: no matching constructor for initialization of 'std::ifstream'
```
system/incremental_delivery/incfs/incfsdump/dump.cpp:238:78: error: no matching constructor for initialization of 'std::ifstream' (aka 'basic_ifstream<char>')
  238 |           : mBackingFile(android::base::Basename(std::string(backingFile))), mIn(backingFile) {}
      |                                                                              ^   ~~~~~~~~~~~
```
Flag: EXEMPT b/353528991 b/371014646
Bug: b/353528991 b/371014646

Change-Id: I7e73f433451f9361b9ffd4e4dae2a835b06b7a82
(cherry picked from commit 1c4f443533aedad8da7f90308baf3e03a9b182cd)