Turn off unused-but-set-variable warning for hardening-benchmark
Clang reports the following errors:

system/incremental_delivery/incfs/tests/hardening_benchmark.cpp:54:9: error: variable 'val' set but not used [-Werror,-Wunused-but-set-variable]
   54 |     int val = 0;
      |         ^
system/incremental_delivery/incfs/tests/hardening_benchmark.cpp:64:9: error: variable 'val' set but not used [-Werror,-Wunused-but-set-variable]
   64 |     int val = 0;

Test: presubmit
Bug: 429520052
Change-Id: Ia1aa5fadf2c92935bdf8766f4f73b0298f1a9539